export const TEXT = {
  COMMON: {
    LOADING: 'Đang tải dữ liệu...',
    ERROR: 'Đã có lỗi xảy ra.',
    RETRY: 'Thử lại',
    SAVE: 'Lưu',
    CANCEL: 'Hủy',
    CONFIRM: 'Xác nhận',
    SUCCESS: 'Thành công',
    BACK_HOME: 'Về trang chủ',
  },
  AUTH: {
    APP_TAGLINE: 'Kết nối mentor dành cho sinh viên',
    LOGIN_TITLE: 'Chào mừng trở lại!',
    LOGIN_SUBTITLE: 'Vui lòng đăng nhập để tiếp tục.',
    LOGIN_CTA: 'Đăng nhập',
    LOGIN_EMPTY: 'Vui lòng nhập đầy đủ email và mật khẩu.',
    REGISTER_TITLE: 'Tạo tài khoản mới',
    REGISTER_SUBTITLE: 'Tham gia cộng đồng UniShare ngay hôm nay.',
    REGISTER_CTA: 'Đăng ký ngay',
    REGISTER_EMPTY: 'Vui lòng nhập đầy đủ thông tin.',
    REGISTER_SUCCESS: 'Đăng ký thành công! Đang chuyển hướng...',
    FORGOT_PASSWORD: 'Quên mật khẩu?',
    NO_ACCOUNT: 'Chưa có tài khoản?',
    HAVE_ACCOUNT: 'Đã có tài khoản?',
    REGISTER_LINK: 'Đăng ký miễn phí',
    LOGIN_LINK: 'Đăng nhập ngay',
  },
  MENTOR: {
    LIST_HERO_TITLE: 'Kết nối với Mentor hàng đầu',
    LIST_HERO_SUBTITLE: 'Nhận tư vấn 1-1 để bứt phá trong học tập và sự nghiệp.',
    SEARCH_PLACEHOLDER: 'Tìm theo tên, chuyên môn...',
    EMPTY_TITLE: 'Không tìm thấy mentor',
    EMPTY_DESCRIPTION: 'Thử tìm kiếm với từ khóa khác hoặc xóa bộ lọc.',
    DETAIL_TITLE: 'Chi tiết mentor',
    VERIFIED: 'Đã xác thực',
    DEFAULT_HEADLINE: 'Chuyên gia',
    NO_BIO: 'Chưa có thông tin giới thiệu.',
    SERVICES_TITLE: 'Các gói dịch vụ',
    PRICE_FROM: 'Giá từ',
    DURATION: 'Thời lượng',
    VIEW_PACKAGE: 'Xem chi tiết và đặt lịch',
    NO_SERVICES: 'Mentor chưa cung cấp gói dịch vụ nào.',
  },
  PROFILE: {
    TITLE: 'Hồ sơ cá nhân',
    EDIT_TITLE: 'Chỉnh sửa hồ sơ',
    EDIT_CTA: 'Chỉnh sửa hồ sơ',
    LOGOUT_TITLE: 'Đăng xuất',
    LOGOUT_CONFIRM: 'Bạn có chắc chắn muốn thoát phiên đăng nhập?',
    LOGOUT_CTA: 'Đăng xuất',
    BASIC_INFO: 'THÔNG TIN CƠ BẢN',
    CHANGE_AVATAR: 'Thay đổi ảnh',
    SAVE_CHANGES: 'Lưu thay đổi',
    SAVE_SUCCESS: 'Đã cập nhật hồ sơ.',
    LOAD_ERROR: 'Không thể tải hồ sơ.',
    SAVE_ERROR: 'Không thể lưu hồ sơ.',
    MENTOR_PENDING_TITLE: 'Tài khoản mentor đang chờ admin duyệt',
    MENTOR_PENDING_DESCRIPTION:
      'Trạng thái hiện tại: {status}. Bạn vẫn có thể dùng app với vai trò người dùng thông thường.',
    DASHBOARD: 'Bảng điều khiển',
    GENERAL: 'Chung',
    USER_LABEL: 'Người dùng',
    GUEST_LABEL: 'Khách',
    CERTIFICATE_EXP: 'Chứng chỉ và kinh nghiệm',
    CERTIFICATE_EXP_SUB: 'Cập nhật lịch sử làm việc',
    ACCOUNT_SETTINGS: 'Cài đặt tài khoản',
    HELP_CENTER: 'Trung tâm trợ giúp',
  },
  BOOKING: {
    LIST_TITLE: 'Lịch hẹn của tôi',
    HEADER_DETAIL: 'Chi tiết lịch hẹn',
    TIMELINE_TITLE: 'Lộ trình buổi học',
    BTN_JOIN: 'Vào họp',
    BTN_REVIEW: 'Đánh giá',
    BTN_COMPLETE: 'Đã xong',
    REVIEW_TITLE: 'Đánh giá buổi học',
    REVIEW_SUBMIT: 'Gửi đánh giá',
    REVIEW_PLACEHOLDER: 'Chia sẻ cảm nhận của bạn...',
    REVIEW_SUCCESS: 'Cảm ơn bạn đã gửi đánh giá!',
    NO_SESSIONS: 'Không có buổi học nào.',
    NO_MEETING: 'Mentor chưa cung cấp link.',
    OPEN_LINK_ERROR: 'Không thể mở link meeting.',
    CREATED_AT: 'Ngày tạo',
    ORDER_CODE: 'Mã đơn',
    STATUS: 'Trạng thái chung',
    PAYMENT_SUCCESS: 'Thanh toán thành công',
    PAYMENT_CANCELLED: 'Thanh toán đã hủy',
    PAYMENT_PENDING: 'Đang chờ xác nhận',
    PAYMENT_SUCCESS_DESC: 'Lịch hẹn đã được tạo. Bạn có thể xem chi tiết trong tab Lịch hẹn.',
    PAYMENT_CANCELLED_DESC: 'Giao dịch chưa hoàn tất. Bạn có thể quay lại gói học để thử lại.',
    PAYMENT_PENDING_DESC:
      'Hệ thống đang xác minh kết quả thanh toán. Vui lòng kiểm tra lại sau ít phút.',
    VIEW_BOOKINGS: 'Xem lịch hẹn',
  },
  PACKAGE: {
    DETAIL_TITLE: 'Chi tiết gói dịch vụ',
    VERSION_TITLE: 'Chọn phiên bản gói học',
    SLOT_TITLE: 'Chọn khung giờ',
    CURRICULUM_TITLE: 'Lộ trình buổi học',
    TOTAL_PAYMENT: 'Tổng thanh toán',
    PAY_NOW: 'Thanh toán ngay',
    NO_SLOT: 'Chưa có khung giờ khả dụng cho phiên bản gói học này.',
    NO_CURRICULUM: 'Chưa có lộ trình chi tiết cho phiên bản gói học này.',
    PACKAGE_NOT_FOUND: 'Không tìm thấy gói dịch vụ.',
    PACKAGE_LOAD_ERROR: 'Không thể tải chi tiết gói dịch vụ.',
    PACKAGE_LOAD_LOADING: 'Đang tải chi tiết gói dịch vụ...',
    SLOT_LOADING: 'Đang tải lịch trống...',
    SELECT_VERSION: 'Vui lòng chọn một phiên bản gói dịch vụ.',
    SELECT_SLOT: 'Vui lòng chọn một khung giờ còn trống trước khi thanh toán.',
    PAYMENT_URL_ERROR: 'Không lấy được URL thanh toán.',
    PAYMENT_ERROR: 'Đã có lỗi xảy ra trong quá trình thanh toán.',
    DEFAULT_DESCRIPTION: 'Mentor sẽ cập nhật mô tả chi tiết cho gói học này sau.',
    DEFAULT_CURRICULUM_DESCRIPTION: 'Nội dung sẽ được mentor cập nhật thêm.',
  },
  MESSAGE: {
    TITLE: 'Tin nhắn',
    SEARCH_PLACEHOLDER: 'Tìm kiếm tin nhắn...',
    ALL: 'Tất cả',
    UNREAD: 'Chưa đọc',
    SESSION: 'Lịch hẹn',
    SESSION_TAG: 'Phiên học',
    EMPTY: 'Không tìm thấy cuộc hội thoại nào',
  },
  HOME: {
    HERO_TITLE_PREFIX: 'Tìm kiếm ',
    HERO_TITLE_HIGHLIGHT: 'Mentor',
    HERO_TITLE_SUFFIX: '\nphù hợp cho bạn',
    HERO_SUBTITLE:
      'Kết nối với những người đi trước giàu kinh nghiệm để nhận lời khuyên, định hướng và học hỏi.',
    HERO_CTA: 'Khám phá Mentor',
    WHY_US: 'Tại sao chọn UniShare?',
  },
  REPORT: {
    TITLE: 'Báo cáo vi phạm',
    ENTITY_TYPE_LABEL: 'Loại đối tượng',
    REASON_LABEL: 'Lý do',
    REASON_PLACEHOLDER: 'Chọn hoặc nhập lý do báo cáo...',
    DESCRIPTION_LABEL: 'Mô tả chi tiết',
    DESCRIPTION_PLACEHOLDER: 'Mô tả cụ thể vấn đề bạn gặp phải...',
    EVIDENCE_LABEL: 'Bằng chứng (tùy chọn)',
    SUBMIT: 'Gửi báo cáo',
    SUCCESS: 'Báo cáo đã được gửi thành công.',
    ERROR: 'Không thể gửi báo cáo. Vui lòng thử lại.',
    LOAD_ERROR: 'Không thể tải danh sách báo cáo.',
    EMPTY: 'Chưa có báo cáo nào.',
  },
  DISPUTE: {
    TITLE: 'Khiếu nại giao dịch',
    REASON_LABEL: 'Lý do khiếu nại',
    REASON_PLACEHOLDER: 'Nhập lý do khiếu nại...',
    DESCRIPTION_LABEL: 'Mô tả chi tiết',
    DESCRIPTION_PLACEHOLDER: 'Mô tả cụ thể vấn đề để admin có thể xử lý...',
    RELATED_BOOKING: 'Lịch hẹn liên quan',
    SUBMIT: 'Gửi khiếu nại',
    SUCCESS: 'Khiếu nại đã được gửi thành công.',
    ERROR: 'Không thể gửi khiếu nại. Vui lòng thử lại.',
  },
  PROGRESS: {
    LIST_TITLE: 'Tiến độ học tập',
    DETAIL_TITLE: 'Chi tiết tiến độ',
    EMPTY: 'Chưa có báo cáo tiến độ nào.',
    MENTOR_FEEDBACK: 'Phản hồi từ mentor',
    NO_FEEDBACK: 'Mentor chưa gửi phản hồi.',
    STATUS_DRAFT: 'Bản nháp',
    STATUS_SUBMITTED: 'Đã gửi',
    STATUS_REVIEWED: 'Đã đánh giá',
    LOAD_ERROR: 'Không thể tải báo cáo tiến độ.',
  },
  DASHBOARD: {
    WELCOME: 'Xin chào',
    UPCOMING_SESSIONS: 'Buổi học sắp tới',
    ACTIVE_BOOKINGS: 'Lịch hẹn đang hoạt động',
    QUICK_ACTIONS: 'Thao tác nhanh',
    FIND_MENTOR: 'Tìm mentor',
    VIEW_BOOKINGS: 'Xem lịch hẹn',
    VIEW_MESSAGES: 'Tin nhắn',
    NO_UPCOMING: 'Không có buổi học nào sắp tới.',
    NO_BOOKINGS: 'Chưa có lịch hẹn nào.',
  },
  MENTOR_DASHBOARD: {
    TITLE: 'Mentor Dashboard',
    SUBTITLE: 'Quản lý hoạt động mentoring của bạn.',
    SESSIONS_COMPLETED: 'Đã hoàn thành',
    ACTIVE_BOOKINGS: 'Đang hoạt động',
    AVG_RATING: 'Đánh giá TB',
    TOTAL_PACKAGES: 'Gói dịch vụ',
    MANAGE_PACKAGES: 'Quản lý gói dịch vụ',
    VIEW_BOOKINGS: 'Lịch hẹn mentor',
    EDIT_PROFILE: 'Chỉnh sửa hồ sơ mentor',
    VIEW_PROGRESS: 'Tiến độ học viên',
    UPCOMING_SESSIONS: 'Buổi học sắp tới',
    NO_UPCOMING: 'Không có buổi học sắp tới.',
    VERIFICATION_VERIFIED: 'Đã xác thực',
    VERIFICATION_PENDING: 'Đang chờ duyệt',
    VERIFICATION_REJECTED: 'Bị từ chối',
  },
  MENTOR_PROFILE: {
    TITLE: 'Hồ sơ Mentor',
    HEADLINE_LABEL: 'CHỨC DANH MENTOR',
    HEADLINE_PLACEHOLDER: 'VD: Senior React Native Developer',
    EXPERTISE_LABEL: 'CHUYÊN MÔN',
    EXPERTISE_PLACEHOLDER: 'React Native, TypeScript, System Design...',
    EXPERTISE_HINT: 'Phân tách bằng dấu phẩy',
    BASE_PRICE_LABEL: 'GIÁ CƠ BẢN ($)',
    BASE_PRICE_PLACEHOLDER: '50',
    SAVE: 'Lưu hồ sơ mentor',
    SAVE_SUCCESS: 'Đã cập nhật hồ sơ mentor.',
    SAVE_ERROR: 'Không thể lưu hồ sơ mentor.',
    LOAD_ERROR: 'Không thể tải hồ sơ mentor.',
    VERIFICATION_STATUS: 'Trạng thái xác thực',
  },
  MENTOR_FEEDBACK: {
    TITLE: 'Gửi phản hồi',
    FEEDBACK_LABEL: 'NỘI DUNG PHẢN HỒI',
    FEEDBACK_PLACEHOLDER: 'Nhận xét tiến độ và gợi ý cho học viên...',
    SUBMIT: 'Gửi phản hồi',
    SUCCESS: 'Phản hồi đã được gửi thành công.',
    ERROR: 'Không thể gửi phản hồi. Vui lòng thử lại.',
  },
} as const;
