export const TEXT = {
  COMMON: {
    LOADING: 'Đang tải dữ liệu...',
    ERROR: 'Đã có lỗi xảy ra',
    RETRY: 'Thử lại',
    SAVE: 'Lưu',
    CANCEL: 'Hủy',
    CONFIRM: 'Xác nhận',
    SUCCESS: 'Thành công',
  },
  SERVICE: {
    LIST_TITLE: 'Gói dịch vụ của bạn',
    EMPTY_STATE: 'Bạn chưa tạo gói dịch vụ nào.',
    CREATE_NEW: 'Tạo gói mới',
    FORM_TITLE_ADD: 'Tạo Gói Dịch Vụ Mới',
    FORM_TITLE_EDIT: 'Sửa Gói Dịch Vụ',
    NAME_LABEL: 'Tên gói',
    NAME_PLACEHOLDER: 'VD: Tư vấn lộ trình Frontend 1-1',
    DESC_LABEL: 'Mô tả',
    DESC_PLACEHOLDER: 'Mô tả chi tiết những gì học viên sẽ nhận được',
    PRICE_LABEL: 'Giá (VND)',
    DURATION_LABEL: 'Thời lượng mỗi buổi (Phút)',
    CURRICULUM_SECTION: 'Giáo trình & Lộ trình học',
    ADD_SESSION: '+ Thêm buổi học',
    SESSION_TITLE_PLACEHOLDER: 'Tên buổi học (VD: Đánh giá năng lực)',
    SESSION_DESC_PLACEHOLDER: 'Nội dung chi tiết...',
    VALIDATION: {
      NAME_REQUIRED: 'Vui lòng nhập tên gói dịch vụ.',
      CURRICULUM_MIN: 'Giáo trình cần ít nhất 1 buổi học.',
      PRICE_MIN: 'Giá không hợp lệ.',
    },
    TOGGLE_SUCCESS: 'Đã cập nhật trạng thái gói.',
    SAVE_SUCCESS: 'Lưu gói dịch vụ thành công.',
    EDIT_WARNING_TITLE: 'Lưu thay đổi gói dịch vụ',
    EDIT_WARNING_MESSAGE:
      'Nếu gói dịch vụ này đã có người mua, thay đổi của bạn sẽ chỉ áp dụng cho khách hàng mới.',
  },
  BOOKING: {
    LIST_TITLE: 'Lịch hẹn của tôi',
    TOTAL_COUNT: 'tổng lịch hẹn',
    TAB_UPCOMING: 'Sắp tới',
    TAB_COMPLETED: 'Hoàn thành',
    TAB_CANCELLED: 'Đã hủy',
    EMPTY_UPCOMING: 'Không có lịch hẹn sắp tới nào.',
    EMPTY_COMPLETED: 'Chưa có lịch hẹn nào hoàn thành.',
    EMPTY_CANCELLED: 'Không có lịch hẹn đã hủy.',
    HEADER_DETAIL: 'Chi tiết Lịch hẹn',
    TIMELINE_TITLE: 'Lộ trình buổi học',
    BTN_JOIN: 'Vào họp',
    BTN_REVIEW: 'Đánh giá',
    BTN_COMPLETE: 'Đã xong',
    REVIEW_MODAL_TITLE: 'Đánh giá buổi học',
    REVIEW_SUBMIT: 'Gửi đánh giá',
    REVIEW_PLACEHOLDER: 'Chia sẻ cảm nhận của bạn...',
    LOAD_ERROR: 'Không thể tải lịch hẹn.',
    UPDATE_STATUS_ERROR: 'Không thể cập nhật trạng thái.',
    LOADING_DETAIL: 'Đang tải lịch hẹn...',
    ORDER_CODE_LABEL: 'Mã đơn:',
    CREATED_AT_LABEL: 'Ngày tạo:',
    OVERALL_STATUS_LABEL: 'Trạng thái chung:',
    EMPTY_SESSIONS: 'Không có buổi học nào.',
    LINK_ERROR_TITLE: 'Lỗi',
    OPEN_MEETING_ERROR: 'Không thể mở đường dẫn lớp học.',
    NO_MEETING_LINK_TITLE: 'Chưa có đường dẫn',
    NO_MEETING_LINK_MESSAGE: 'Chuyên gia chưa cung cấp đường dẫn lớp học.',
    SESSION_PREFIX: 'Buổi ',
    UNSCHEDULED: 'Chưa xếp lịch',
    REVIEW_SUCCESS: 'Cảm ơn bạn đã đánh giá!',
  },
  MESSAGES: {
    SCREEN_TITLE: 'Tin nhắn',
    SEARCH_PLACEHOLDER: 'Tìm kiếm cuộc hội thoại...',
    TAB_ALL: 'Tất cả',
    TAB_UNREAD: 'Chưa đọc',
    TAB_BOOKING: 'Lịch hẹn',
    BADGE_BOOKING: 'Đặt lịch',
    BADGE_GENERAL: 'Chung',
    BADGE_SUPPORT: 'Hỗ trợ',
    EMPTY_STATE: 'Bạn chưa có cuộc hội thoại nào',
    EMPTY_SEARCH: 'Không tìm thấy cuộc hội thoại phù hợp',
    INPUT_PLACEHOLDER: 'Nhập tin nhắn...',
    STATUS_ONLINE: 'Đang hoạt động',
    STATUS_OFFLINE: 'Ngoại tuyến',
    SENT_IMAGE: 'Đã gửi một hình ảnh',
    SENT_FILE: 'Đã gửi một tệp tin',
    BOOKING_INFO_TITLE: 'Thông tin lịch hẹn',
    VIEW_BOOKING: 'Xem chi tiết',
    LOAD_ERROR: 'Không thể tải cuộc hội thoại. Vui lòng thử lại.',
    SEND_ERROR: 'Không thể gửi tin nhắn. Vui lòng thử lại.',
  },
  PROGRESS_REPORT: {
    LIST_TITLE: 'Báo cáo tiến độ',
    DETAIL_TITLE: 'Chi tiết báo cáo',
    TAB_ALL: 'Tất cả',
    TAB_PENDING: 'Chờ phản hồi',
    TAB_REVIEWED: 'Đã phản hồi',
    STATUS_SUBMITTED: 'Chờ phản hồi',
    STATUS_REVIEWED: 'Đã phản hồi',
    STATUS_NEEDS_REVISION: 'Cần chỉnh sửa',
    MENTEE_LABEL: 'Học viên',
    CREATED_AT_LABEL: 'Tạo lúc',
    CONTENT_TITLE: 'Nội dung báo cáo',
    ATTACHMENT_LABEL: 'Tệp đính kèm',
    FEEDBACK_TITLE: 'Phản hồi của bạn',
    FEEDBACK_PLACEHOLDER: 'Nhập nhận xét và phản hồi cho học viên...',
    FEEDBACK_EXISTING_TITLE: 'Phản hồi trước đó',
    EVALUATION_LABEL: 'Đánh giá',
    EVALUATION_REVIEWED: 'Đạt yêu cầu',
    EVALUATION_NEEDS_REVISION: 'Cần chỉnh sửa',
    SUBMIT_FEEDBACK: 'Gửi phản hồi',
    EDIT_FEEDBACK: 'Sửa phản hồi',
    SUBMIT_SUCCESS: 'Đã gửi phản hồi thành công!',
    SUBMIT_ERROR: 'Không thể gửi phản hồi. Vui lòng thử lại.',
    VALIDATION_FEEDBACK_REQUIRED: 'Vui lòng nhập nội dung phản hồi.',
    VALIDATION_STATUS_REQUIRED: 'Vui lòng chọn đánh giá.',
    EMPTY_STATE: 'Chưa có báo cáo tiến độ nào từ học viên.',
    LOAD_ERROR: 'Không thể tải báo cáo. Vui lòng thử lại.',
  },
  VALIDATION: {
    REQUIRED: 'Trường này không được để trống.',
  },
  MENTOR_PROFILE: {
    TITLE: 'Hồ sơ chuyên gia',
    LOADING: 'Đang tải hồ sơ chuyên gia...',
    DESCRIPTION:
      'Cập nhật thông tin chuyên môn để học viên và quản trị viên có thể đánh giá hồ sơ của bạn chính xác hơn.',
    STATUS_CARD_LABEL: 'Trạng thái xác thực',
    STATUS_PENDING: 'Đang chờ duyệt',
    STATUS_PENDING_DESC:
      'Hồ sơ chuyên gia của bạn đang được quản trị viên xem xét. Bạn vẫn có thể cập nhật thông tin trước khi được phê duyệt.',
    STATUS_VERIFIED: 'Đã xác thực',
    STATUS_VERIFIED_DESC:
      'Hồ sơ chuyên gia của bạn đã được xác thực và sẵn sàng hiển thị trên nền tảng.',
    STATUS_REJECTED: 'Bị từ chối',
    STATUS_REJECTED_DESC:
      'Hồ sơ chuyên gia chưa được phê duyệt. Vui lòng rà soát lại nội dung, cập nhật thông tin cần thiết và gửi lại yêu cầu duyệt.',
    SECTION_TITLE: 'Thông tin chuyên môn',
    SECTION_DESCRIPTION:
      'Vui lòng điền đầy đủ tiêu đề chuyên môn, kỹ năng nổi bật và mức giá cơ bản theo giờ.',
    HEADLINE_LABEL: 'Tiêu đề chuyên môn',
    HEADLINE_PLACEHOLDER: 'Ví dụ: Kỹ sư phần mềm Senior tại Google',
    HEADLINE_HELPER:
      'Tiêu đề nên thể hiện rõ vai trò chuyên môn, lĩnh vực và kinh nghiệm nổi bật của bạn.',
    EXPERTISE_LABEL: 'Kỹ năng chuyên môn',
    EXPERTISE_PLACEHOLDER: 'Ví dụ: React Native, Node.js, Luyện phỏng vấn',
    EXPERTISE_HELPER:
      'Nhập các kỹ năng cách nhau bằng dấu phẩy để hệ thống hiển thị và hỗ trợ tìm kiếm.',
    BASE_PRICE_LABEL: 'Mức giá cơ bản / giờ',
    BASE_PRICE_PLACEHOLDER: 'Ví dụ: 300000',
    BASE_PRICE_HELPER:
      'Đây là mức giá tham khảo theo giờ dành cho dịch vụ mentoring cơ bản của bạn.',
    VERIFYING_NOTE:
      'Sau khi gửi yêu cầu duyệt, quản trị viên sẽ xem xét hồ sơ của bạn trước khi hiển thị công khai.',
    BUTTON_SAVE: 'Lưu thay đổi',
    BUTTON_SUBMIT: 'Gửi yêu cầu duyệt',
    ALERT_TITLE_ERROR: 'Không thể xử lý',
    ALERT_TITLE_SUCCESS: 'Đã lưu thành công',
    ALERT_TITLE_SUBMITTED: 'Đã gửi yêu cầu duyệt',
    ALERT_LOAD_ERROR: 'Không thể tải hồ sơ chuyên gia. Vui lòng thử lại sau.',
    ALERT_SAVE_SUCCESS: 'Thông tin hồ sơ chuyên gia đã được cập nhật.',
    ALERT_SAVE_ERROR: 'Không thể lưu hồ sơ chuyên gia. Vui lòng thử lại sau.',
    ALERT_SUBMIT_SUCCESS:
      'Hồ sơ chuyên gia đã được gửi tới quản trị viên để xem xét và phê duyệt.',
    ALERT_SUBMIT_ERROR: 'Không thể gửi yêu cầu duyệt hồ sơ. Vui lòng thử lại sau.',
    VALIDATION_HEADLINE_REQUIRED: 'Vui lòng nhập tiêu đề chuyên môn.',
    VALIDATION_EXPERTISE_REQUIRED: 'Vui lòng nhập kỹ năng chuyên môn.',
    VALIDATION_BASE_PRICE_REQUIRED: 'Vui lòng nhập mức giá cơ bản theo giờ.',
    VALIDATION_BASE_PRICE_INVALID: 'Mức giá cơ bản phải là một số dương hợp lệ.',
  },
  MENTOR_DASHBOARD: {
    TITLE: 'Bảng điều khiển chuyên gia',
    SUBTITLE: 'Theo dõi nhanh lịch dạy, gói dịch vụ và hiệu suất mentoring của bạn.',
    LOADING: 'Đang tải bảng điều khiển...',
    LOAD_ERROR: 'Không thể tải dữ liệu bảng điều khiển. Vui lòng thử lại sau.',
    ACTIVE_BOOKINGS: 'Lịch hẹn đang hoạt động',
    UPCOMING_SESSIONS: 'Buổi học sắp tới',
    ACTIVE_SERVICES: 'Gói dịch vụ đang hoạt động',
    AVERAGE_RATING: 'Điểm đánh giá trung bình',
    EMPTY_RATING: 'Chưa có đánh giá',
    QUICK_LINKS: 'Lối tắt',
    GO_TO_SERVICES: 'Quản lý gói dịch vụ',
    GO_TO_BOOKINGS: 'Xem lịch hẹn',
    GO_TO_PROFILE: 'Hồ sơ chuyên gia',
    PULL_TO_REFRESH: 'Kéo xuống để làm mới',
  },
  AUTH_OTP: {
    TITLE: 'Xác thực OTP',
    SUBTITLE:
      'Mã xác thực đã được gửi đến email của bạn. Vui lòng nhập mã để tiếp tục.',
    RESEND_PROMPT: 'Không nhận được mã? ',
    RESEND_COUNTDOWN: 'Gửi lại sau {seconds}s',
    RESEND_NOW: 'Gửi lại ngay',
    VERIFY_BUTTON: 'Xác nhận',
    VERIFY_SUCCESS_TITLE: 'Xác thực thành công',
    VERIFY_SUCCESS_MESSAGE: 'Mã OTP đã được xác thực. Vui lòng đăng nhập để tiếp tục.',
    VERIFY_ERROR_TITLE: 'Không thể xác thực',
    VERIFY_ERROR_MESSAGE: 'Không thể xác thực mã OTP. Vui lòng thử lại.',
    RESEND_SUCCESS_TITLE: 'Đã gửi lại mã',
    RESEND_SUCCESS_MESSAGE: 'Mã OTP mới đã được gửi tới email của bạn.',
    RESEND_ERROR_TITLE: 'Không thể gửi lại mã',
    RESEND_ERROR_MESSAGE: 'Không thể gửi lại mã OTP. Vui lòng thử lại sau.',
    EMAIL_REQUIRED_MESSAGE: 'Không tìm thấy email để gửi lại mã xác thực.',
    INVALID_CODE_MESSAGE: 'Vui lòng nhập đầy đủ 6 chữ số của mã OTP.',
  },
  PACKAGE_DETAIL: {
    NOT_FOUND: 'Không tìm thấy gói dịch vụ.',
    PAYMENT_URL_MISSING: 'Không tìm thấy đường dẫn thanh toán.',
    CHECKOUT_SUCCESS_TITLE: 'Thành công',
    CHECKOUT_SUCCESS_MESSAGE: 'Đặt chỗ thành công!',
    VIEW_BOOKINGS: 'Xem lịch hẹn',
    ERROR_TITLE: 'Lỗi',
    LOGIN_REQUIRED: 'Vui lòng đăng nhập trước khi thanh toán.',
    HEADER_TITLE: 'Chi tiết gói dịch vụ',
    DURATION_TITLE: 'Chọn thời lượng',
    CURRICULUM_TITLE: 'Lộ trình chi tiết',
    CURRICULUM_FALLBACK: 'Nội dung buổi học đang được cập nhật.',
    TOTAL_LABEL: 'Tổng thanh toán',
    PAY_NOW: 'Thanh toán ngay',
  },
  MENTOR_DETAIL: {
    LOAD_ERROR: 'Không thể tải chi tiết chuyên gia.',
    LOADING: 'Đang tải dữ liệu chuyên gia...',
    NOT_FOUND: 'Không tìm thấy hồ sơ chuyên gia.',
    HEADER_TITLE: 'Chi tiết chuyên gia',
    DEFAULT_HEADLINE: 'Chuyên gia',
    VERIFIED: 'Đã xác thực',
    DEFAULT_BIO: 'Chưa có thông tin giới thiệu.',
    RATING: 'Điểm đánh giá',
    COMPLETED_SESSIONS: 'Buổi đã hoàn thành',
    EXPERTISE: 'Kỹ năng chuyên môn',
    EDUCATION: 'Học vấn',
    EXPERIENCE: 'Kinh nghiệm',
    CERTIFICATE: 'Chứng chỉ',
    PACKAGES: 'Các gói dịch vụ',
    EMPTY_PACKAGES: 'Chuyên gia chưa cung cấp gói dịch vụ nào.',
    STARTING_FROM: 'Bắt đầu từ',
    NO_ADDITIONAL_INFO: 'Chưa có thông tin để hiển thị.',
  },
  SERVICE_VERSION: {
    PACKAGE_STATUS_LABEL: 'Trạng thái gói dịch vụ',
    PACKAGE_STATUS_ACTIVE: 'Đang hoạt động - đang hiển thị để mentor quản lý',
    PACKAGE_STATUS_INACTIVE: 'Tạm ẩn - gói dịch vụ đang bị ẩn',
    PACKAGE_VERSIONS_TITLE: 'CÁC PHIÊN BẢN GÓI DỊCH VỤ',
    PACKAGE_VERSIONS_SUMMARY:
      'Gói dịch vụ này hiện có {count} phiên bản. Hãy quản lý giá, thời lượng, trạng thái mặc định và giáo trình trong màn quản lý phiên bản.',
    PACKAGE_VERSIONS_CREATE_HINT:
      'Sau khi tạo gói dịch vụ cha, hệ thống sẽ đưa bạn sang màn quản lý phiên bản để thêm phiên bản đầu tiên.',
    MANAGE_VERSIONS: 'Quản lý phiên bản',
    SAVE_AND_OPEN_VERSIONS: 'Lưu gói dịch vụ và mở danh sách phiên bản',
    CREATE_PACKAGE: 'Tạo gói dịch vụ',
    VERSIONS_SCREEN_TITLE: 'Các phiên bản gói dịch vụ',
    LOAD_VERSIONS_ERROR: 'Không thể tải danh sách phiên bản.',
    EMPTY_VERSIONS:
      'Gói dịch vụ này chưa có phiên bản nào. Hãy tạo phiên bản đầu tiên để bắt đầu bán.',
    ADD_VERSION: 'Thêm phiên bản mới',
    EDIT_VERSION: 'Sửa',
    SET_DEFAULT: 'Đặt mặc định',
    DELETE_VERSION: 'Xóa',
    BADGE_DEFAULT: 'Mặc định',
    BADGE_ACTIVE: 'Đang hoạt động',
    BADGE_INACTIVE: 'Tạm ẩn',
    BADGE_HAS_ORDER: 'Đã có đơn mua',
    BADGE_EDITABLE: 'Có thể chỉnh sửa',
    VERSION_LABEL: 'Phiên bản',
    DELIVERY_TYPE: 'Hình thức triển khai',
    WARNING_VERSION_HAS_ORDER:
      'Phiên bản này đã có người mua. Khi lưu thay đổi, hệ thống sẽ tạo phiên bản mới thay vì sửa đè.',
    DELETE_CONFIRM_TITLE: 'Xóa phiên bản',
    DELETE_CONFIRM_MESSAGE: 'Bạn có chắc muốn xóa phiên bản {id}?',
    DELETE_ERROR_TITLE: 'Không thể xóa',
    SET_DEFAULT_ERROR_TITLE: 'Không thể đặt mặc định',
    NO_DESCRIPTION: 'Chưa có mô tả.',
    VERSION_EDITOR_ADD_TITLE: 'Thêm phiên bản gói dịch vụ',
    VERSION_EDITOR_EDIT_TITLE: 'Sửa phiên bản gói dịch vụ',
    VERSION_LOADING: 'Đang tải phiên bản...',
    VERSION_STATUS_TITLE: 'Trạng thái phiên bản',
    VERSION_STATUS_CLONE:
      'Phiên bản này đã có đơn mua. Khi lưu thay đổi, hệ thống sẽ tạo phiên bản mới.',
    VERSION_STATUS_EDITABLE: 'Phiên bản này có thể chỉnh sửa trực tiếp.',
    VERSION_INFO_TITLE: 'THÔNG TIN PHIÊN BẢN',
    PRICE_LABEL: 'GIÁ (VND)',
    DURATION_LABEL: 'THỜI LƯỢNG (PHÚT)',
    DELIVERY_TYPE_LABEL: 'HÌNH THỨC TRIỂN KHAI',
    DELIVERY_TYPE_PLACEHOLDER: 'ONLINE',
    DELIVERY_TYPE_HELPER: 'Phiên bản V1 cho phép nhập văn bản đơn giản, mặc định là ONLINE',
    DEFAULT_TOGGLE_TITLE: 'Đặt làm mặc định',
    DEFAULT_TOGGLE_DESC: 'Phiên bản mặc định để bán cho khách hàng mới',
    ACTIVE_TOGGLE_TITLE: 'Trạng thái hoạt động',
    ACTIVE_TOGGLE_DESC: 'Bật để hiển thị phiên bản này trên marketplace',
    VERSION_SAVE_SUCCESS: 'Đã cập nhật phiên bản.',
    VERSION_CREATE_SUCCESS: 'Đã tạo phiên bản {id}.',
    VERSION_CLONE_SUCCESS: 'Đã tạo phiên bản mới {id} vì bản gốc đã có đơn mua.',
    VERSION_SAVE_ERROR: 'Không thể lưu phiên bản.',
    SAVE_VERSION: 'Lưu phiên bản',
    CREATE_VERSION: 'Tạo phiên bản',
    VALIDATION_PRICE: 'Giá phải là số dương.',
    VALIDATION_DURATION: 'Thời lượng phải là số dương.',
  },
  CURRICULUM: {
    TITLE: 'GIÁO TRÌNH',
    ADD_ITEM: '+ Thêm học phần',
    ITEM_LABEL: 'Học phần {index}',
    TITLE_LABEL: 'TIÊU ĐỀ',
    TITLE_PLACEHOLDER: 'VD: Đánh giá năng lực',
    DESCRIPTION_LABEL: 'MÔ TẢ',
    DESCRIPTION_PLACEHOLDER: 'Nội dung chi tiết...',
    DURATION_LABEL: 'THỜI LƯỢNG',
    DURATION_PLACEHOLDER: '30',
    MIN_REQUIRED: 'Giáo trình cần ít nhất 1 học phần.',
    TITLE_REQUIRED: 'Tiêu đề học phần không được để trống.',
  },
};
