export const TEXT = {
  COMMON: {
    LOADING: 'Đang tải dữ liệu...',
    ERROR: 'Đã có lỗi xảy ra.',
    RETRY: 'Thử lại',
    SAVE: 'Lưu',
    CANCEL: 'Hủy',
    CONFIRM: 'Xác nhận',
    SUCCESS: 'Thành công',
    BACK_HOME: 'Về trang chủ',
  },
  AUTH: {
    APP_TAGLINE: 'Kết nối mentor dành cho sinh viên',
    LOGIN_TITLE: 'Chào mừng trở lại!',
    LOGIN_SUBTITLE: 'Vui lòng đăng nhập để tiếp tục.',
    LOGIN_CTA: 'Đăng nhập',
    LOGIN_EMPTY: 'Vui lòng nhập đầy đủ email và mật khẩu.',
    REGISTER_TITLE: 'Tạo tài khoản mới',
    REGISTER_SUBTITLE: 'Tham gia cộng đồng UniShare ngay hôm nay.',
    REGISTER_CTA: 'Đăng ký ngay',
    REGISTER_EMPTY: 'Vui lòng nhập đầy đủ thông tin.',
    REGISTER_SUCCESS: 'Đăng ký thành công! Đang chuyển hướng...',
    FORGOT_PASSWORD: 'Quên mật khẩu?',
    NO_ACCOUNT: 'Chưa có tài khoản?',
    HAVE_ACCOUNT: 'Đã có tài khoản?',
    REGISTER_LINK: 'Đăng ký miễn phí',
    LOGIN_LINK: 'Đăng nhập ngay',
  },
  MENTOR: {
    LIST_HERO_TITLE: 'Kết nối với Mentor hàng đầu',
    LIST_HERO_SUBTITLE: 'Nhận tư vấn 1-1 để bứt phá trong học tập và sự nghiệp.',
    SEARCH_PLACEHOLDER: 'Tìm theo tên, chuyên môn...',
    EMPTY_TITLE: 'Không tìm thấy mentor',
    EMPTY_DESCRIPTION: 'Thử tìm kiếm với từ khóa khác hoặc xóa bộ lọc.',
    DETAIL_TITLE: 'Chi tiết mentor',
    VERIFIED: 'Đã xác thực',
    DEFAULT_HEADLINE: 'Chuyên gia',
    NO_BIO: 'Chưa có thông tin giới thiệu.',
    SERVICES_TITLE: 'Các gói dịch vụ',
    PRICE_FROM: 'Giá từ',
    DURATION: 'Thời lượng',
    VIEW_PACKAGE: 'Xem chi tiết và đặt lịch',
    NO_SERVICES: 'Mentor chưa cung cấp gói dịch vụ nào.',
  },
  PROFILE: {
    TITLE: 'Hồ sơ cá nhân',
    EDIT_TITLE: 'Chỉnh sửa hồ sơ',
    EDIT_CTA: 'Chỉnh sửa hồ sơ',
    LOGOUT_TITLE: 'Đăng xuất',
    LOGOUT_CONFIRM: 'Bạn có chắc chắn muốn thoát phiên đăng nhập?',
    LOGOUT_CTA: 'Đăng xuất',
    BASIC_INFO: 'THÔNG TIN CƠ BẢN',
    CHANGE_AVATAR: 'Thay đổi ảnh',
    SAVE_CHANGES: 'Lưu thay đổi',
    SAVE_SUCCESS: 'Đã cập nhật hồ sơ.',
    LOAD_ERROR: 'Không thể tải hồ sơ.',
    SAVE_ERROR: 'Không thể lưu hồ sơ.',
    MENTOR_PENDING_TITLE: 'Tài khoản mentor đang chờ admin duyệt',
    MENTOR_PENDING_DESCRIPTION:
      'Trạng thái hiện tại: {status}. Bạn vẫn có thể dùng app với vai trò người dùng thông thường.',
    DASHBOARD: 'Bảng điều khiển',
    GENERAL: 'Chung',
    USER_LABEL: 'Người dùng',
    GUEST_LABEL: 'Khách',
    CERTIFICATE_EXP: 'Chứng chỉ và kinh nghiệm',
    CERTIFICATE_EXP_SUB: 'Cập nhật lịch sử làm việc',
    ACCOUNT_SETTINGS: 'Cài đặt tài khoản',
    HELP_CENTER: 'Trung tâm trợ giúp',
  },
  BOOKING: {
    LIST_TITLE: 'Lịch hẹn của tôi',
    HEADER_DETAIL: 'Chi tiết lịch hẹn',
    TIMELINE_TITLE: 'Lộ trình buổi học',
    BTN_JOIN: 'Vào họp',
    BTN_REVIEW: 'Đánh giá',
    BTN_COMPLETE: 'Đã xong',
    REVIEW_TITLE: 'Đánh giá buổi học',
    REVIEW_SUBMIT: 'Gửi đánh giá',
    REVIEW_PLACEHOLDER: 'Chia sẻ cảm nhận của bạn...',
    REVIEW_SUCCESS: 'Cảm ơn bạn đã gửi đánh giá!',
    NO_SESSIONS: 'Không có buổi học nào.',
    NO_MEETING: 'Mentor chưa cung cấp link.',
    OPEN_LINK_ERROR: 'Không thể mở link meeting.',
    CREATED_AT: 'Ngày tạo',
    ORDER_CODE: 'Mã đơn',
    STATUS: 'Trạng thái chung',
    PAYMENT_SUCCESS: 'Thanh toán thành công',
    PAYMENT_CANCELLED: 'Thanh toán đã hủy',
    PAYMENT_PENDING: 'Đang chờ xác nhận',
    PAYMENT_SUCCESS_DESC: 'Lịch hẹn đã được tạo. Bạn có thể xem chi tiết trong tab Lịch hẹn.',
    PAYMENT_CANCELLED_DESC: 'Giao dịch chưa hoàn tất. Bạn có thể quay lại gói học để thử lại.',
    PAYMENT_PENDING_DESC:
      'Hệ thống đang xác minh kết quả thanh toán. Vui lòng kiểm tra lại sau ít phút.',
    VIEW_BOOKINGS: 'Xem lịch hẹn',
  },
  PACKAGE: {
    DETAIL_TITLE: 'Chi tiết gói dịch vụ',
    VERSION_TITLE: 'Chọn phiên bản gói học',
    SLOT_TITLE: 'Chọn khung giờ',
    CURRICULUM_TITLE: 'Lộ trình buổi học',
    TOTAL_PAYMENT: 'Tổng thanh toán',
    PAY_NOW: 'Thanh toán ngay',
    NO_SLOT: 'Chưa có khung giờ khả dụng cho phiên bản gói học này.',
    NO_CURRICULUM: 'Chưa có lộ trình chi tiết cho phiên bản gói học này.',
    PACKAGE_NOT_FOUND: 'Không tìm thấy gói dịch vụ.',
    PACKAGE_LOAD_ERROR: 'Không thể tải chi tiết gói dịch vụ.',
    PACKAGE_LOAD_LOADING: 'Đang tải chi tiết gói dịch vụ...',
    SLOT_LOADING: 'Đang tải lịch trống...',
    SELECT_VERSION: 'Vui lòng chọn một phiên bản gói dịch vụ.',
    SELECT_SLOT: 'Vui lòng chọn một khung giờ còn trống trước khi thanh toán.',
    PAYMENT_URL_ERROR: 'Không lấy được URL thanh toán.',
    PAYMENT_ERROR: 'Đã có lỗi xảy ra trong quá trình thanh toán.',
    DEFAULT_DESCRIPTION: 'Mentor sẽ cập nhật mô tả chi tiết cho gói học này sau.',
    DEFAULT_CURRICULUM_DESCRIPTION: 'Nội dung sẽ được mentor cập nhật thêm.',
  },
  MESSAGE: {
    TITLE: 'Tin nhắn',
    SEARCH_PLACEHOLDER: 'Tìm kiếm tin nhắn...',
    ALL: 'Tất cả',
    UNREAD: 'Chưa đọc',
    SESSION: 'Lịch hẹn',
    SESSION_TAG: 'Phiên học',
    EMPTY: 'Không tìm thấy cuộc hội thoại nào',
  },
  HOME: {
    HERO_TITLE_PREFIX: 'Tìm kiếm ',
    HERO_TITLE_HIGHLIGHT: 'Mentor',
    HERO_TITLE_SUFFIX: '\nphù hợp cho bạn',
    HERO_SUBTITLE:
      'Kết nối với những người đi trước giàu kinh nghiệm để nhận lời khuyên, định hướng và học hỏi.',
    HERO_CTA: 'Khám phá Mentor',
    WHY_US: 'Tại sao chọn UniShare?',
  },
} as const;
